### PR TITLE
My-Assignment-4

### PR DESCRIPTION
**Pull request by rilwanhaq**
Assignment-4
Assignment-4 2

### CODE REVIEW

**Review by 10534549 — COMMENTED** [review]
your code seems good but in the output screen it shows like u divided the page into 2 div  can u look into it again

**Comment by rilwanhaq** [comment]
> your code seems good but in the output screen it shows like u divided the page into 2 div can u look into it again

no its bcs it is having scroll bar so i took screnshots like that and i have used different background image so its bigger than usual image

**Comment by 10534549** [comment]
> > your code seems good but in the output screen it shows like u divided the page into 2 div can u look into it again
> 
> no its bcs it is having scroll bar so i took screnshots like that and i have used different background image so its bigger than usual image

ok then everything else is good

**Comment by SuneetKumar19** [comment]
Great Work! Looks quite impressive.

**Comment by rilwanhaq** [comment]
> Great Work! Looks quite impressive.

thank you sir

**Pull request merged**
